// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spaceport;

namespace Spaceport.Migrations
{
    [DbContext(typeof(StarwarsDBContext))]
    [Migration("20200320142033_ISpaceShipID_fix")]
    partial class ISpaceShipID_fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spaceport.ParkingSession", b =>
                {
                    b.Property<int>("ParkingSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParkingSpotID")
                        .HasColumnType("int");

                    b.Property<bool>("ParkingToken")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpacePortID")
                        .HasColumnType("int");

                    b.HasKey("ParkingSessionID");

                    b.HasIndex("ParkingSpotID");

                    b.HasIndex("SpacePortID");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("Spaceport.ParkingSpot", b =>
                {
                    b.Property<int>("ParkingSpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("SpacePortID")
                        .HasColumnType("int");

                    b.HasKey("ParkingSpotID");

                    b.HasIndex("SpacePortID");

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("Spaceport.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Spaceport.SpacePort", b =>
                {
                    b.Property<int>("SpacePortID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpacePortID");

                    b.ToTable("Spaceports");
                });

            modelBuilder.Entity("Spaceport.StarShip", b =>
                {
                    b.Property<int>("SpaceShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DriverPersonID")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("SpaceShipID");

                    b.HasIndex("DriverPersonID");

                    b.ToTable("StarShip");
                });

            modelBuilder.Entity("Spaceport.ParkingSession", b =>
                {
                    b.HasOne("Spaceport.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotID");

                    b.HasOne("Spaceport.SpacePort", "SpacePort")
                        .WithMany()
                        .HasForeignKey("SpacePortID");
                });

            modelBuilder.Entity("Spaceport.ParkingSpot", b =>
                {
                    b.HasOne("Spaceport.SpacePort", null)
                        .WithMany("ParkingSpots")
                        .HasForeignKey("SpacePortID");
                });

            modelBuilder.Entity("Spaceport.StarShip", b =>
                {
                    b.HasOne("Spaceport.Person", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverPersonID");
                });
#pragma warning restore 612, 618
        }
    }
}
